ModLoader.SetupFileHook( "lua/Player_Client.lua", "lua/Joshua-Boo-Boos Lerk Lift Mod/Player_Client.lua", "post" )
ModLoader.SetupFileHook( "lua/Player_Server.lua", "lua/Joshua-Boo-Boos Lerk Lift Mod/Player_Server.lua", "post" )
ModLoader.SetupFileHook( "lua/Alien.lua", "lua/Joshua-Boo-Boos Lerk Lift Mod/Alien.lua", "replace" )
ModLoader.SetupFileHook( "lua/Marine.lua", "lua/Joshua-Boo-Boos Lerk Lift Mod/Marine.lua", "replace" )
ModLoader.SetupFileHook( "lua/GUIAlienHUD.lua", "lua/Joshua-Boo-Boos Lerk Lift Mod/GUIAlienHUD.lua", "replace" )